pipeline {
    agent any

    stages {
        stage('Pull') {
            steps {
                git 'https://github.com/Sudarshan-Mane-2004/Test-Jenkins.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying'
            }
        }
    }
}
